development:
  adapter: postgresql
  encoding: unicode
  database: crambear_development
  pool: 5
  username: postgres
  password: 
  host: 
  port: 5432

test: &test
  adapter: postgresql
  encoding: unicode
  database: crambear_test
  pool: 5
  username: postgres
  password: 
  host: 
  port: 5432


